#!/usr/bin/env bash
# jira adapter configuration
# Generated by setup wizard on 2026-04-01

# Status ID -> display name
STATUS_10108=Agent
STATUS_10107=Refined
STATUS_10103="To Do"
STATUS_10104="In Progress"
STATUS_10105=Done
STATUS_10106=Backlog
STATUS_10109=QA

# How to transition a card TO each status (transition IDs)
